// B1 seviyesi kelime ve paragraf veri kaynağı.
// Her yenilemede rastgele, tekrarsız (havuz bitene kadar) içerik seçilir.

const WORDS = [
  { word: "achieve", tr: "başarmak", syn: ["accomplish", "attain"], ant: ["fail"], ex: "She worked hard to achieve her goals.", exTr: "Hedeflerine ulaşmak için çok çalıştı." },
  { word: "improve", tr: "geliştirmek, iyileştirmek", syn: ["enhance", "better"], ant: ["worsen"], ex: "He wants to improve his English skills.", exTr: "İngilizce becerilerini geliştirmek istiyor." },
  { word: "increase", tr: "artırmak, artmak", syn: ["rise", "grow"], ant: ["decrease"], ex: "The company increased its profits this year.", exTr: "Şirket bu yıl kârını artırdı." },
  { word: "decrease", tr: "azaltmak, azalmak", syn: ["reduce", "decline"], ant: ["increase"], ex: "The number of visitors decreased in winter.", exTr: "Ziyaretçi sayısı kışın azaldı." },
  { word: "reliable", tr: "güvenilir", syn: ["dependable", "trustworthy"], ant: ["unreliable"], ex: "This is a reliable source of information.", exTr: "Bu güvenilir bir bilgi kaynağıdır." },
  { word: "efficient", tr: "verimli", syn: ["effective", "productive"], ant: ["inefficient"], ex: "The new engine is more efficient than the old one.", exTr: "Yeni motor eskisinden daha verimli." },
  { word: "complex", tr: "karmaşık", syn: ["complicated", "intricate"], ant: ["simple"], ex: "The project turned out to be more complex than expected.", exTr: "Proje beklenenden daha karmaşık çıktı." },
  { word: "flexible", tr: "esnek", syn: ["adaptable", "adjustable"], ant: ["rigid"], ex: "We need a flexible schedule for this job.", exTr: "Bu iş için esnek bir programa ihtiyacımız var." },
  { word: "essential", tr: "gerekli, temel", syn: ["necessary", "vital"], ant: ["unnecessary"], ex: "Water is essential for life.", exTr: "Su, yaşam için gereklidir." },
  { word: "avoid", tr: "kaçınmak", syn: ["evade", "prevent"], ant: ["face"], ex: "Try to avoid making the same mistake twice.", exTr: "Aynı hatayı iki kez yapmaktan kaçınmaya çalış." },
  { word: "reduce", tr: "azaltmak", syn: ["decrease", "cut"], ant: ["increase"], ex: "We must reduce our energy consumption.", exTr: "Enerji tüketimimizi azaltmalıyız." },
  { word: "develop", tr: "geliştirmek", syn: ["create", "build"], ant: ["abandon"], ex: "Engineers developed a new method for testing bridges.", exTr: "Mühendisler köprüleri test etmek için yeni bir yöntem geliştirdi." },
  { word: "maintain", tr: "sürdürmek, bakımını yapmak", syn: ["sustain", "preserve"], ant: ["neglect"], ex: "Regular maintenance helps maintain the machine's performance.", exTr: "Düzenli bakım, makinenin performansını sürdürmeye yardımcı olur." },
  { word: "durable", tr: "dayanıklı", syn: ["sturdy", "tough"], ant: ["fragile"], ex: "This material is very durable and lasts for years.", exTr: "Bu malzeme çok dayanıklıdır ve yıllarca dayanır." },
  { word: "fragile", tr: "kırılgan", syn: ["delicate", "breakable"], ant: ["durable"], ex: "Be careful, the glass is fragile.", exTr: "Dikkat et, cam kırılgandır." },
  { word: "accurate", tr: "doğru, kesin", syn: ["precise", "correct"], ant: ["inaccurate"], ex: "The measurements must be accurate.", exTr: "Ölçümler kesin olmalıdır." },
  { word: "estimate", tr: "tahmin etmek", syn: ["guess", "calculate"], ant: ["confirm"], ex: "Can you estimate how long this will take?", exTr: "Bunun ne kadar süreceğini tahmin edebilir misin?" },
  { word: "construct", tr: "inşa etmek", syn: ["build", "assemble"], ant: ["destroy"], ex: "Workers constructed the building in six months.", exTr: "İşçiler binayı altı ayda inşa ettiler." },
  { word: "destroy", tr: "yok etmek", syn: ["demolish", "ruin"], ant: ["construct"], ex: "The storm destroyed several houses.", exTr: "Fırtına birkaç evi yıktı." },
  { word: "innovative", tr: "yenilikçi", syn: ["creative", "original"], ant: ["conventional"], ex: "The company is known for its innovative products.", exTr: "Şirket yenilikçi ürünleriyle tanınır." },
  { word: "traditional", tr: "geleneksel", syn: ["conventional", "classic"], ant: ["modern"], ex: "They still use traditional farming methods.", exTr: "Hâlâ geleneksel tarım yöntemlerini kullanıyorlar." },
  { word: "adapt", tr: "uyum sağlamak", syn: ["adjust", "modify"], ant: ["resist"], ex: "Animals adapt to their environment over time.", exTr: "Hayvanlar zamanla çevrelerine uyum sağlar." },
  { word: "resist", tr: "direnmek, karşı koymak", syn: ["oppose", "withstand"], ant: ["yield"], ex: "The material can resist high temperatures.", exTr: "Malzeme yüksek sıcaklıklara dayanabilir." },
  { word: "combine", tr: "birleştirmek", syn: ["mix", "merge"], ant: ["separate"], ex: "Combine the two chemicals carefully.", exTr: "İki kimyasalı dikkatlice birleştirin." },
  { word: "separate", tr: "ayırmak", syn: ["divide", "split"], ant: ["combine"], ex: "Separate the recyclable materials from the waste.", exTr: "Geri dönüştürülebilir malzemeleri atıktan ayırın." },
  { word: "analyze", tr: "analiz etmek", syn: ["examine", "study"], ant: ["ignore"], ex: "Scientists analyzed the data carefully.", exTr: "Bilim insanları verileri dikkatlice analiz etti." },
  { word: "predict", tr: "tahmin etmek, öngörmek", syn: ["forecast", "anticipate"], ant: ["ignore"], ex: "It's hard to predict the weather next month.", exTr: "Gelecek ayki havayı tahmin etmek zor." },
  { word: "reveal", tr: "ortaya çıkarmak", syn: ["expose", "disclose"], ant: ["conceal"], ex: "The report revealed some surprising facts.", exTr: "Rapor bazı şaşırtıcı gerçekleri ortaya çıkardı." },
  { word: "conceal", tr: "gizlemek", syn: ["hide", "cover"], ant: ["reveal"], ex: "She tried to conceal her disappointment.", exTr: "Hayal kırıklığını gizlemeye çalıştı." },
  { word: "generous", tr: "cömert", syn: ["giving", "charitable"], ant: ["selfish"], ex: "He is generous with his time and money.", exTr: "Zamanı ve parası konusunda cömerttir." },
  { word: "selfish", tr: "bencil", syn: ["self-centered", "greedy"], ant: ["generous"], ex: "It was selfish of him not to share.", exTr: "Paylaşmaması bencilceydi." },
  { word: "brave", tr: "cesur", syn: ["courageous", "fearless"], ant: ["cowardly"], ex: "The firefighter was brave enough to enter the burning building.", exTr: "İtfaiyeci, yanan binaya girecek kadar cesurdu." },
  { word: "cowardly", tr: "korkak", syn: ["fearful", "timid"], ant: ["brave"], ex: "It was cowardly of him to run away.", exTr: "Kaçması korkakçaydı." },
  { word: "ancient", tr: "antik, eski", syn: ["old", "historic"], ant: ["modern"], ex: "They discovered an ancient temple in the forest.", exTr: "Ormanda antik bir tapınak keşfettiler." },
  { word: "modern", tr: "modern", syn: ["contemporary", "current"], ant: ["ancient"], ex: "The city has many modern buildings.", exTr: "Şehirde birçok modern bina var." },
  { word: "wealthy", tr: "zengin", syn: ["rich", "affluent"], ant: ["poor"], ex: "She comes from a wealthy family.", exTr: "Zengin bir aileden geliyor." },
  { word: "poor", tr: "fakir", syn: ["needy", "impoverished"], ant: ["wealthy"], ex: "Many people in the region are poor.", exTr: "Bölgedeki birçok insan fakir." },
  { word: "calm", tr: "sakin", syn: ["peaceful", "relaxed"], ant: ["anxious"], ex: "Try to stay calm during the exam.", exTr: "Sınav sırasında sakin kalmaya çalış." },
  { word: "anxious", tr: "endişeli", syn: ["nervous", "worried"], ant: ["calm"], ex: "She felt anxious before the interview.", exTr: "Mülakat öncesinde endişeliydi." },
  { word: "curious", tr: "meraklı", syn: ["inquisitive", "interested"], ant: ["indifferent"], ex: "Children are naturally curious about the world.", exTr: "Çocuklar doğası gereği dünya hakkında meraklıdır." },
  { word: "indifferent", tr: "kayıtsız", syn: ["unconcerned", "apathetic"], ant: ["curious"], ex: "He seemed indifferent to the news.", exTr: "Habere karşı kayıtsız görünüyordu." },
  { word: "cautious", tr: "dikkatli, temkinli", syn: ["careful", "wary"], ant: ["careless"], ex: "Drivers should be cautious in heavy rain.", exTr: "Sürücüler yoğun yağmurda dikkatli olmalıdır." },
  { word: "careless", tr: "dikkatsiz", syn: ["sloppy", "negligent"], ant: ["cautious"], ex: "A careless mistake caused the accident.", exTr: "Dikkatsiz bir hata kazaya neden oldu." },
  { word: "capable", tr: "yetenekli", syn: ["competent", "skilled"], ant: ["incapable"], ex: "She is capable of solving difficult problems.", exTr: "Zor problemleri çözebilecek yetenektedir." },
  { word: "incapable", tr: "yeteneksiz, aciz", syn: ["unable", "incompetent"], ant: ["capable"], ex: "He seemed incapable of finishing the task.", exTr: "Görevi bitirmekten aciz görünüyordu." },
  { word: "sufficient", tr: "yeterli", syn: ["enough", "adequate"], ant: ["insufficient"], ex: "We have sufficient evidence to support the theory.", exTr: "Teoriyi desteklemek için yeterli kanıtımız var." },
  { word: "insufficient", tr: "yetersiz", syn: ["inadequate", "lacking"], ant: ["sufficient"], ex: "The funding was insufficient for the project.", exTr: "Finansman proje için yetersizdi." },
  { word: "gradual", tr: "kademeli, yavaş yavaş", syn: ["slow", "steady"], ant: ["sudden"], ex: "There has been a gradual increase in temperature.", exTr: "Sıcaklıkta kademeli bir artış oldu." },
  { word: "sudden", tr: "ani", syn: ["abrupt", "unexpected"], ant: ["gradual"], ex: "There was a sudden change in the weather.", exTr: "Havada ani bir değişiklik oldu." },
  { word: "sustainable", tr: "sürdürülebilir", syn: ["renewable", "viable"], ant: ["unsustainable"], ex: "We need sustainable solutions for energy production.", exTr: "Enerji üretimi için sürdürülebilir çözümlere ihtiyacımız var." },
  { word: "renewable", tr: "yenilenebilir", syn: ["sustainable", "replenishable"], ant: ["non-renewable"], ex: "Solar power is a renewable energy source.", exTr: "Güneş enerjisi yenilenebilir bir enerji kaynağıdır." },
  { word: "precise", tr: "kesin, hassas", syn: ["exact", "accurate"], ant: ["vague"], ex: "Engineers need precise measurements.", exTr: "Mühendislerin kesin ölçümlere ihtiyacı vardır." },
  { word: "vague", tr: "belirsiz", syn: ["unclear", "imprecise"], ant: ["precise"], ex: "His explanation was too vague to understand.", exTr: "Açıklaması anlaşılmayacak kadar belirsizdi." },
  { word: "crucial", tr: "çok önemli, kritik", syn: ["vital", "critical"], ant: ["unimportant"], ex: "Safety checks are crucial in construction.", exTr: "Güvenlik kontrolleri inşaatta kritik önemdedir." },
  { word: "minor", tr: "önemsiz, küçük", syn: ["small", "insignificant"], ant: ["major"], ex: "It was just a minor problem.", exTr: "Sadece küçük bir sorundu." },
  { word: "major", tr: "büyük, önemli", syn: ["significant", "main"], ant: ["minor"], ex: "This is a major breakthrough in technology.", exTr: "Bu, teknolojide büyük bir atılımdır." },
  { word: "inevitable", tr: "kaçınılmaz", syn: ["unavoidable", "certain"], ant: ["avoidable"], ex: "Change is inevitable in every industry.", exTr: "Değişim her sektörde kaçınılmazdır." },
  { word: "optional", tr: "isteğe bağlı", syn: ["voluntary", "elective"], ant: ["mandatory"], ex: "Attendance at the meeting is optional.", exTr: "Toplantıya katılım isteğe bağlıdır." },
  { word: "mandatory", tr: "zorunlu", syn: ["compulsory", "required"], ant: ["optional"], ex: "Wearing a helmet is mandatory on this site.", exTr: "Bu sahada kask takmak zorunludur." },
];

const PARAGRAPHS = [
  {
    category: "story",
    title: "The Lost Key",
    titleTr: "Kayıp Anahtar",
    en: "Maria was getting ready for work when she realized she couldn't find her keys. She searched her bag, the kitchen table, and even under the sofa, but the keys were nowhere. After twenty minutes of panic, she remembered that she had left them in her coat pocket from the day before. She laughed at herself and hurried out the door, only ten minutes late. From that day on, she always kept a spare key in her bag.",
    tr: "Maria işe gitmeye hazırlanırken anahtarlarını bulamadığını fark etti. Çantasını, mutfak masasını ve hatta koltuğun altını aradı ama anahtarlar hiçbir yerde yoktu. Yirmi dakikalık panikten sonra, anahtarları bir önceki günden kalan mont cebinde bıraktığını hatırladı. Kendine güldü ve sadece on dakika geç kalarak kapıdan aceleyle çıktı. O günden sonra çantasında her zaman yedek bir anahtar taşıdı.",
  },
  {
    category: "story",
    title: "A Trip to the Mountains",
    titleTr: "Dağlara Bir Gezi",
    en: "Last summer, Ahmet and his friends decided to hike up a mountain near their city. They started early in the morning to avoid the heat. Halfway through the trail, dark clouds appeared, and it started to rain heavily. They found shelter under a large rock and waited until the storm passed. Although they were wet and tired, they reached the top and enjoyed a beautiful view of the valley below.",
    tr: "Geçen yaz, Ahmet ve arkadaşları şehirlerine yakın bir dağa tırmanmaya karar verdiler. Sıcaktan kaçınmak için sabah erkenden yola çıktılar. Patikanın yarısında koyu bulutlar belirdi ve şiddetli yağmur başladı. Büyük bir kayanın altına sığındılar ve fırtına geçene kadar beklediler. Islak ve yorgun olmalarına rağmen zirveye ulaştılar ve aşağıdaki vadinin güzel manzarasının tadını çıkardılar.",
  },
  {
    category: "story",
    title: "The New Neighbor",
    titleTr: "Yeni Komşu",
    en: "When Elif moved into her new apartment, she didn't know anyone in the building. One evening, she heard a knock on her door. It was her neighbor, an elderly man named Mr. Demir, holding a plate of homemade cookies. He welcomed her to the building and offered to help if she ever needed anything. Elif was touched by his kindness, and they soon became good friends.",
    tr: "Elif yeni dairesine taşındığında, binada kimseyi tanımıyordu. Bir akşam kapısının çalındığını duydu. Bu, Bay Demir adında yaşlı bir komşusuydu ve elinde ev yapımı kurabiyeler vardı. Onu binaya hoş geldin dedi ve bir ihtiyacı olursa yardım etmeyi teklif etti. Elif onun nezaketinden çok etkilendi ve kısa sürede iyi arkadaş oldular.",
  },
  {
    category: "story",
    title: "Learning from Failure",
    titleTr: "Başarısızlıktan Öğrenmek",
    en: "When Can was in university, he failed his first programming exam. He felt embarrassed and thought about giving up on computer science. However, his professor told him that failure is a normal part of learning. Can decided to study harder and asked his classmates for help. By the end of the semester, he had become one of the top students in the class.",
    tr: "Can üniversitedeyken ilk programlama sınavında başarısız oldu. Utandı ve bilgisayar bilimini bırakmayı düşündü. Ancak profesörü, başarısızlığın öğrenmenin doğal bir parçası olduğunu söyledi. Can daha çok çalışmaya karar verdi ve sınıf arkadaşlarından yardım istedi. Dönem sonunda sınıfın en iyi öğrencilerinden biri haline gelmişti.",
  },
  {
    category: "story",
    title: "The Power of Habit",
    titleTr: "Alışkanlığın Gücü",
    en: "Zeynep wanted to become healthier, so she decided to start running every morning. In the beginning, it was very difficult, and she wanted to quit after just a few days. Instead, she asked a friend to join her, which made the mornings more enjoyable. After two months, running became a habit, and she even signed up for a small city marathon.",
    tr: "Zeynep daha sağlıklı olmak istedi, bu yüzden her sabah koşmaya başlamaya karar verdi. Başlangıçta çok zordu ve sadece birkaç gün sonra bırakmak istedi. Bunun yerine bir arkadaşından kendisine katılmasını istedi, bu da sabahları daha keyifli hale getirdi. İki ay sonra koşu bir alışkanlık haline geldi ve hatta küçük bir şehir maratonuna kaydoldu.",
  },
  {
    category: "story",
    title: "A Lesson in Honesty",
    titleTr: "Dürüstlük Dersi",
    en: "While shopping, Burak noticed that the cashier had given him too much change. For a moment, he thought about keeping the extra money. But he remembered his mother's words about honesty and returned to the counter. The cashier thanked him warmly and said that not many customers would have done the same. Burak left the store feeling proud of his decision.",
    tr: "Alışveriş yaparken Burak, kasiyerin ona fazla para üstü verdiğini fark etti. Bir an fazla parayı kendine saklamayı düşündü. Ama annesinin dürüstlükle ilgili sözlerini hatırladı ve kasaya geri döndü. Kasiyer ona içtenlikle teşekkür etti ve pek çok müşterinin aynısını yapmayacağını söyledi. Burak dükkândan kararından gurur duyarak ayrıldı.",
  },
  {
    category: "story",
    title: "The Job Interview",
    titleTr: "İş Görüşmesi",
    en: "Selin was very nervous before her first job interview. She prepared answers to common questions and chose her clothes carefully the night before. During the interview, she stayed calm and answered every question honestly. A week later, she received a phone call with good news: she had gotten the job. Her hard work and preparation had paid off.",
    tr: "Selin ilk iş görüşmesinden önce çok gergindi. Yaygın sorulara cevaplar hazırladı ve bir önceki gece kıyafetlerini dikkatle seçti. Görüşme sırasında sakin kaldı ve her soruyu dürüstçe cevapladı. Bir hafta sonra iyi bir haberle telefon aldı: işe alınmıştı. Çabası ve hazırlığı karşılığını vermişti.",
  },
  {
    category: "engineering",
    title: "What is Civil Engineering?",
    titleTr: "İnşaat Mühendisliği Nedir?",
    en: "Civil engineering is the branch of engineering that deals with the design and construction of buildings, roads, bridges, and other structures. Civil engineers must consider safety, cost, and the environment when they plan a project. For example, before building a bridge, engineers study the soil, the weather conditions, and the amount of traffic it will carry. Good civil engineering makes cities safer and more efficient for everyone.",
    tr: "İnşaat mühendisliği, binaların, yolların, köprülerin ve diğer yapıların tasarımı ve inşasıyla ilgilenen mühendislik dalıdır. İnşaat mühendisleri bir proje planlarken güvenliği, maliyeti ve çevreyi göz önünde bulundurmalıdır. Örneğin, bir köprü inşa etmeden önce mühendisler toprağı, hava koşullarını ve taşıyacağı trafik miktarını incelerler. İyi bir inşaat mühendisliği, şehirleri herkes için daha güvenli ve verimli hale getirir.",
  },
  {
    category: "engineering",
    title: "How Electric Motors Work",
    titleTr: "Elektrik Motorları Nasıl Çalışır?",
    en: "An electric motor converts electrical energy into mechanical energy, allowing machines to move. Inside the motor, electricity passes through a coil of wire, creating a magnetic field. This magnetic field interacts with magnets inside the motor, causing the shaft to rotate. Electric motors are used in many devices, from washing machines to electric cars. Because they are efficient and produce less pollution, electric motors are becoming more popular every year.",
    tr: "Elektrik motoru, elektrik enerjisini mekanik enerjiye dönüştürerek makinelerin hareket etmesini sağlar. Motorun içinde elektrik, bir tel bobininden geçerek manyetik bir alan oluşturur. Bu manyetik alan, motorun içindeki mıknatıslarla etkileşime girerek milin dönmesine neden olur. Elektrik motorları çamaşır makinelerinden elektrikli arabalara kadar birçok cihazda kullanılır. Verimli oldukları ve daha az kirlilik ürettikleri için elektrik motorları her yıl daha popüler hale geliyor.",
  },
  {
    category: "engineering",
    title: "The Basics of Software Development",
    titleTr: "Yazılım Geliştirmenin Temelleri",
    en: "Software development is the process of designing, writing, and testing computer programs. Developers usually start by understanding what problem the software needs to solve. Then, they write code using a programming language such as Python or Java. After writing the code, they test it carefully to find and fix any errors, known as bugs. Good software development requires patience, logical thinking, and teamwork.",
    tr: "Yazılım geliştirme, bilgisayar programlarını tasarlama, yazma ve test etme sürecidir. Geliştiriciler genellikle yazılımın hangi sorunu çözmesi gerektiğini anlayarak başlar. Ardından Python veya Java gibi bir programlama dili kullanarak kod yazarlar. Kodu yazdıktan sonra, hata olarak bilinen sorunları bulmak ve düzeltmek için dikkatlice test ederler. İyi bir yazılım geliştirme, sabır, mantıksal düşünme ve ekip çalışması gerektirir.",
  },
  {
    category: "engineering",
    title: "Renewable Energy Sources",
    titleTr: "Yenilenebilir Enerji Kaynakları",
    en: "Renewable energy comes from natural sources that do not run out, such as sunlight, wind, and water. Solar panels capture energy from the sun and convert it into electricity. Wind turbines use the movement of air to generate power. Unlike fossil fuels, renewable energy sources produce little to no pollution. As technology improves, engineers are finding cheaper and more efficient ways to use renewable energy around the world.",
    tr: "Yenilenebilir enerji, güneş ışığı, rüzgar ve su gibi tükenmeyen doğal kaynaklardan gelir. Güneş panelleri güneşten enerji yakalar ve onu elektriğe dönüştürür. Rüzgar türbinleri, elektrik üretmek için havanın hareketini kullanır. Fosil yakıtların aksine, yenilenebilir enerji kaynakları çok az kirlilik üretir veya hiç üretmez. Teknoloji geliştikçe, mühendisler dünya genelinde yenilenebilir enerjiyi kullanmanın daha ucuz ve daha verimli yollarını buluyor.",
  },
  {
    category: "engineering",
    title: "What Do Mechanical Engineers Do?",
    titleTr: "Makine Mühendisleri Ne Yapar?",
    en: "Mechanical engineers design, build, and test machines and mechanical systems. Their work includes everything from small parts, like gears and springs, to large systems, like engines and robots. Mechanical engineers use physics and mathematics to make sure their designs are safe and efficient. They often work closely with other engineers, such as electrical and civil engineers, to complete large projects. This field offers many career opportunities in industries like automotive, aerospace, and manufacturing.",
    tr: "Makine mühendisleri, makineleri ve mekanik sistemleri tasarlar, inşa eder ve test eder. Çalışmaları, dişliler ve yaylar gibi küçük parçalardan motorlar ve robotlar gibi büyük sistemlere kadar her şeyi içerir. Makine mühendisleri, tasarımlarının güvenli ve verimli olmasını sağlamak için fizik ve matematik kullanır. Büyük projeleri tamamlamak için genellikle elektrik ve inşaat mühendisleri gibi diğer mühendislerle yakın çalışırlar. Bu alan, otomotiv, havacılık ve üretim gibi sektörlerde birçok kariyer fırsatı sunar.",
  },
  {
    category: "engineering",
    title: "Understanding Artificial Intelligence",
    titleTr: "Yapay Zekayı Anlamak",
    en: "Artificial intelligence, or AI, refers to computer systems that can perform tasks that normally require human intelligence. These tasks include recognizing speech, making decisions, and solving problems. AI systems learn from large amounts of data instead of following fixed instructions. Today, AI is used in many fields, including healthcare, transportation, and customer service. However, engineers must be careful to design AI systems that are fair, safe, and reliable.",
    tr: "Yapay zeka veya AI, normalde insan zekası gerektiren görevleri yerine getirebilen bilgisayar sistemlerini ifade eder. Bu görevler arasında konuşmayı tanıma, karar verme ve problem çözme yer alır. Yapay zeka sistemleri, sabit talimatları izlemek yerine büyük miktarda veriden öğrenir. Günümüzde yapay zeka, sağlık, ulaşım ve müşteri hizmetleri dahil olmak üzere birçok alanda kullanılmaktadır. Ancak mühendisler, adil, güvenli ve güvenilir yapay zeka sistemleri tasarlamaya dikkat etmelidir.",
  },
  {
    category: "engineering",
    title: "The Importance of Bridge Maintenance",
    titleTr: "Köprü Bakımının Önemi",
    en: "Bridges are essential structures that connect cities and allow people to travel easily. However, bridges face constant stress from traffic, weather, and time, so they need regular maintenance. Engineers inspect bridges to check for cracks, rust, and other signs of damage. If problems are found early, repairs are usually simple and inexpensive. Ignoring maintenance, on the other hand, can lead to serious accidents and expensive repairs in the future.",
    tr: "Köprüler, şehirleri birbirine bağlayan ve insanların kolayca seyahat etmesini sağlayan önemli yapılardır. Ancak köprüler trafik, hava koşulları ve zamandan kaynaklanan sürekli bir strese maruz kalır, bu yüzden düzenli bakıma ihtiyaç duyarlar. Mühendisler, çatlakları, pası ve diğer hasar belirtilerini kontrol etmek için köprüleri denetler. Sorunlar erken tespit edilirse, onarımlar genellikle basit ve ucuzdur. Bakımı ihmal etmek ise gelecekte ciddi kazalara ve pahalı onarımlara yol açabilir.",
  },
];

// Reading/Listening metinlerinde geçen kelimelerin tek tek Türkçe karşılıkları.
// Kelimeye tıklanınca burada aranır (küçük harfe çevrilerek).
const GLOSSARY = {
  a: "bir", about: "hakkında", accident: "kaza", accidents: "kazalar", accurate: "doğru, kesin",
  achieve: "başarmak", adapt: "uyum sağlamak", aerospace: "havacılık ve uzay", after: "sonra",
  ahmet: "Ahmet (isim)", ai: "yapay zekâ (AI)", air: "hava", allow: "izin vermek, sağlamak",
  allowing: "sağlayarak", although: "her ne kadar, -e rağmen", always: "her zaman", amount: "miktar",
  amounts: "miktarlar", an: "bir", analyzed: "analiz etti", ancient: "antik, eski", and: "ve",
  animals: "hayvanlar", answered: "cevapladı", answers: "cevaplar", anxious: "endişeli", any: "herhangi",
  anyone: "herhangi biri", anything: "herhangi bir şey", apartment: "daire", appeared: "belirdi, göründü",
  are: "-dir (olmak fiili)", around: "etrafında", artificial: "yapay", as: "olarak, gibi",
  asked: "sordu, istedi", at: "-de, -da", attendance: "katılım", automotive: "otomotiv",
  avoid: "kaçınmak", away: "uzağa, uzakta", bag: "çanta", be: "olmak", beautiful: "güzel",
  became: "oldu", because: "çünkü", become: "olmak, haline gelmek", becoming: "haline geliyor",
  been: "olmuş", before: "önce", beginning: "başlangıç", below: "aşağıda", branch: "dal, şube",
  brave: "cesur", breakthrough: "atılım, çığır açan gelişme", bridge: "köprü", bridges: "köprüler",
  bugs: "hatalar (yazılımda)", build: "inşa etmek", building: "bina, inşa etmek", buildings: "binalar",
  burak: "Burak (isim)", burning: "yanan", but: "ama, fakat", by: "tarafından, ile", call: "aramak",
  calm: "sakin", can: "-ebilmek", capable: "yetenekli", capture: "yakalamak", career: "kariyer",
  careful: "dikkatli", carefully: "dikkatlice", careless: "dikkatsiz", carry: "taşımak",
  cars: "arabalar", cashier: "kasiyer", caused: "neden oldu", causing: "neden olarak",
  cautious: "dikkatli, temkinli", change: "değişim, değiştirmek", cheaper: "daha ucuz",
  check: "kontrol etmek", checks: "kontroller", chemicals: "kimyasallar", children: "çocuklar",
  chose: "seçti", cities: "şehirler", city: "şehir", civil: "sivil (inşaat mühendisliği)",
  class: "sınıf", classmates: "sınıf arkadaşları", closely: "yakından", clothes: "kıyafetler",
  clouds: "bulutlar", coat: "mont, palto", code: "kod", coil: "bobin", combine: "birleştirmek",
  comes: "gelir", common: "yaygın, ortak", company: "şirket", complete: "tamamlamak",
  complex: "karmaşık", computer: "bilgisayar", conceal: "gizlemek", conditions: "koşullar",
  connect: "bağlamak", consider: "göz önünde bulundurmak", constant: "sürekli",
  constructed: "inşa etti", construction: "inşaat", consumption: "tüketim", convert: "dönüştürmek",
  converts: "dönüştürür", cookies: "kurabiyeler", cost: "maliyet", "couldn't": "yapamadı",
  counter: "tezgah, kasa", cowardly: "korkak", cracks: "çatlaklar", creating: "yaratarak, oluşturarak",
  crucial: "çok önemli, kritik", curious: "meraklı", customer: "müşteri", customers: "müşteriler",
  damage: "hasar", dark: "koyu, karanlık", data: "veri", day: "gün", days: "günler",
  deals: "ilgilenir (deal with)", decided: "karar verdi", decision: "karar", decisions: "kararlar",
  decreased: "azaldı", demir: "Demir (soyisim)", design: "tasarım, tasarlamak",
  designing: "tasarlama", designs: "tasarımlar", destroyed: "yok etti", developed: "geliştirdi",
  developers: "geliştiriciler", development: "geliştirme", devices: "cihazlar",
  "didn't": "yapmadı", difficult: "zor", disappointment: "hayal kırıklığı", discovered: "keşfetti",
  do: "yapmak", done: "yapılmış", door: "kapı", drivers: "sürücüler", durable: "dayanıklı",
  during: "sırasında", early: "erken", easily: "kolayca", efficient: "verimli", elderly: "yaşlı",
  electric: "elektrikli", electrical: "elektrikle ilgili", electricity: "elektrik", elif: "Elif (isim)",
  embarrassed: "utandı, mahcup oldu", end: "son, bitmek", energy: "enerji", engine: "motor",
  engineering: "mühendislik", engineers: "mühendisler", engines: "motorlar", english: "İngilizce",
  enjoyable: "keyifli", enjoyed: "keyfini çıkardı", enough: "yeterli", enter: "girmek",
  environment: "çevre", errors: "hatalar", essential: "gerekli, temel", estimate: "tahmin etmek",
  even: "hatta", evening: "akşam", ever: "hiç", every: "her", everyone: "herkes",
  everything: "her şey", evidence: "kanıt", exam: "sınav", example: "örnek", expected: "beklenen",
  expensive: "pahalı", explanation: "açıklama", extra: "fazladan, ekstra", face: "yüzleşmek, yüz",
  facts: "gerçekler", failed: "başarısız oldu", failure: "başarısızlık", fair: "adil",
  family: "aile", farming: "tarım", feeling: "his, hissetme", felt: "hissetti", few: "birkaç, az",
  field: "alan", fields: "alanlar", find: "bulmak", finding: "bulma", finishing: "bitirme",
  firefighter: "itfaiyeci", first: "ilk", fix: "düzeltmek", fixed: "sabit, düzeltilmiş",
  flexible: "esnek", following: "takip eden, aşağıdaki", for: "için", forest: "orman",
  fossil: "fosil", found: "buldu", fragile: "kırılgan", friend: "arkadaş", friends: "arkadaşlar",
  from: "-den, -dan", fuels: "yakıtlar", funding: "finansman", future: "gelecek", gears: "dişliler",
  generate: "üretmek", generous: "cömert", getting: "alıyor, oluyor", given: "verilmiş",
  giving: "verme, cömert", glass: "cam", goals: "hedefler", good: "iyi", gotten: "almış",
  gradual: "kademeli", habit: "alışkanlık", had: "sahipti", halfway: "yarı yolda", hand: "el",
  hard: "zor, sıkı", harder: "daha sıkı", has: "sahip", have: "sahip olmak", he: "o (erkek)",
  healthcare: "sağlık hizmeti", healthier: "daha sağlıklı", heard: "duydu", heat: "sıcaklık",
  heavily: "şiddetle", heavy: "ağır, yoğun", helmet: "kask", help: "yardım etmek",
  helps: "yardımcı olur", her: "onun (kadın)", herself: "kendisi (kadın)", high: "yüksek",
  hike: "doğa yürüyüşü yapmak", him: "onu (erkek)", his: "onun (erkek)", holding: "elinde tutan",
  homemade: "ev yapımı", honestly: "dürüstçe", honesty: "dürüstlük", houses: "evler",
  how: "nasıl", however: "ancak, bununla birlikte", human: "insan", hurried: "aceleyle gitti",
  if: "eğer", ignoring: "göz ardı ederek", improve: "geliştirmek, iyileştirmek",
  improves: "geliştirir", in: "içinde", incapable: "yeteneksiz, aciz", include: "içermek",
  includes: "içerir", including: "dahil olmak üzere", increase: "artırmak", increased: "artırdı",
  indifferent: "kayıtsız", industries: "endüstriler", industry: "endüstri",
  inevitable: "kaçınılmaz", inexpensive: "ucuz", information: "bilgi", innovative: "yenilikçi",
  inside: "içinde", inspect: "denetlemek", instead: "bunun yerine", instructions: "talimatlar",
  insufficient: "yetersiz", intelligence: "zekâ", interacts: "etkileşime girer",
  interview: "mülakat", into: "içine", is: "-dir (olmak)", it: "o (nesne)", "it's": "o (it is)",
  its: "onun (nesne)", java: "Java (programlama dili)", job: "iş", join: "katılmak",
  just: "sadece", keeping: "saklama, tutma", kept: "sakladı, tuttu", key: "anahtar",
  keys: "anahtarlar", kindness: "nezaket", kitchen: "mutfak", knock: "kapı çalma", know: "bilmek",
  known: "bilinen", language: "dil", large: "büyük", last: "geçen, son", lasts: "dayanır, sürer",
  late: "geç", later: "sonra, daha sonra", laughed: "güldü", lead: "yol açmak", learn: "öğrenmek",
  learning: "öğrenme", left: "bıraktı, sol", less: "daha az", life: "hayat", like: "gibi, hoşlanmak",
  little: "küçük, az", logical: "mantıksal", long: "uzun", "machine's": "makinenin",
  machines: "makineler", made: "yaptı", magnetic: "manyetik", magnets: "mıknatıslar",
  maintain: "sürdürmek", maintenance: "bakım", major: "büyük, önemli", make: "yapmak",
  makes: "yapar", making: "yapma", man: "adam", mandatory: "zorunlu",
  manufacturing: "üretim, imalat", many: "birçok", marathon: "maraton", maria: "Maria (isim)",
  material: "malzeme", materials: "malzemeler", mathematics: "matematik",
  measurements: "ölçümler", mechanical: "mekanik", meeting: "toplantı", method: "yöntem",
  methods: "yöntemler", minor: "önemsiz, küçük", minutes: "dakikalar", mistake: "hata",
  modern: "modern", moment: "an", money: "para", month: "ay", months: "aylar", more: "daha fazla",
  morning: "sabah", mornings: "sabahlar", "mother's": "annesinin", motor: "motor",
  motors: "motorlar", mountain: "dağ", move: "hareket etmek", moved: "taşındı",
  movement: "hareket", mr: "Bay", much: "çok", must: "-meli, -malı", named: "adında, isimli",
  natural: "doğal", naturally: "doğal olarak", near: "yakın", need: "ihtiyaç duymak",
  needed: "ihtiyaç duydu", needs: "ihtiyaç duyar", neighbor: "komşu", nervous: "gergin",
  new: "yeni", news: "haber", next: "sonraki", night: "gece", no: "hayır", normal: "normal",
  normally: "normalde", not: "değil", noticed: "fark etti", nowhere: "hiçbir yerde",
  number: "sayı", of: "-in, -ın (aitlik)", off: "kapalı, uzağa", offered: "teklif etti",
  offers: "sunar", often: "sık sık", old: "eski, yaşlı", on: "üzerinde", one: "bir, biri",
  only: "sadece", opportunities: "fırsatlar", optional: "isteğe bağlı", or: "veya",
  other: "diğer", our: "bizim", out: "dışarı", over: "üzerinden, bitmiş", paid: "ödedi, karşılığını verdi",
  panels: "paneller", panic: "panik", part: "parça", parts: "parçalar", passed: "geçti",
  passes: "geçer", patience: "sabır", people: "insanlar", perform: "gerçekleştirmek",
  performance: "performans", phone: "telefon", physics: "fizik", plan: "plan, planlamak",
  plate: "tabak", pocket: "cep", pollution: "kirlilik", poor: "fakir", popular: "popüler",
  power: "güç", precise: "kesin, hassas", predict: "tahmin etmek", preparation: "hazırlık",
  prepared: "hazırladı, hazırlanmış", problem: "sorun", problems: "sorunlar", process: "süreç",
  produce: "üretmek", production: "üretim", products: "ürünler", professor: "profesör",
  profits: "kârlar", programming: "programlama", programs: "programlar", project: "proje",
  projects: "projeler", proud: "gururlu", python: "Python (programlama dili)", question: "soru",
  questions: "sorular", quit: "bırakmak, vazgeçmek", rain: "yağmur", reached: "ulaştı",
  ready: "hazır", realized: "fark etti", received: "aldı", recognizing: "tanıma",
  recyclable: "geri dönüştürülebilir", reduce: "azaltmak", refers: "ifade eder", region: "bölge",
  regular: "düzenli", reliable: "güvenilir", remembered: "hatırladı", renewable: "yenilenebilir",
  repairs: "onarımlar", report: "rapor", require: "gerektirmek", requires: "gerektirir",
  resist: "direnmek", returned: "geri döndü", revealed: "ortaya çıkardı", roads: "yollar",
  robots: "robotlar", rock: "kaya", rotate: "dönmek", run: "koşmak", running: "koşu, koşma",
  rust: "pas", safe: "güvenli", safer: "daha güvenli", safety: "güvenlik", said: "dedi",
  same: "aynı", schedule: "program, çizelge", science: "bilim", scientists: "bilim insanları",
  searched: "aradı", seemed: "görünüyordu", selfish: "bencil", selin: "Selin (isim)",
  semester: "dönem (akademik)", separate: "ayırmak", serious: "ciddi", service: "hizmet",
  several: "birkaç, çeşitli", shaft: "mil (mekanik parça)", share: "paylaşmak", she: "o (kadın)",
  shelter: "sığınak", shopping: "alışveriş", should: "-meli, -malı (tavsiye)",
  signed: "imzaladı, kaydoldu", signs: "belirtiler, işaretler", simple: "basit", site: "saha, alan",
  six: "altı", skills: "beceriler", small: "küçük", so: "bu yüzden", sofa: "koltuk",
  software: "yazılım", soil: "toprak", solar: "güneş (enerjisi)", solutions: "çözümler",
  solve: "çözmek", solving: "çözme", some: "bazı", soon: "yakında, kısa sürede", source: "kaynak",
  sources: "kaynaklar", spare: "yedek", speech: "konuşma", springs: "yaylar", start: "başlamak",
  started: "başladı", stay: "kalmak", stayed: "kaldı", still: "hâlâ", storm: "fırtına",
  store: "dükkan, mağaza", stress: "stres, gerilim", structures: "yapılar", students: "öğrenciler",
  study: "çalışmak, incelemek", such: "böyle, gibi", sudden: "ani", sufficient: "yeterli",
  summer: "yaz", sun: "güneş", sunlight: "güneş ışığı", support: "desteklemek", sure: "emin",
  surprising: "şaşırtıcı", sustainable: "sürdürülebilir", systems: "sistemler", table: "masa",
  take: "almak", task: "görev", tasks: "görevler", teamwork: "ekip çalışması",
  technology: "teknoloji", temperature: "sıcaklık", temperatures: "sıcaklıklar", temple: "tapınak",
  ten: "on", test: "test etmek", testing: "test etme", than: "-den (karşılaştırma)",
  thanked: "teşekkür etti", that: "o, ki", the: "(belirli tanımlık)", their: "onların",
  them: "onları", then: "sonra", theory: "teori", there: "orada", these: "bunlar", they: "onlar",
  thinking: "düşünme", this: "bu", thought: "düşündü", through: "içinden, boyunca", time: "zaman",
  tired: "yorgun", to: "-e, -a (yönelme)", today: "bugün", told: "söyledi", too: "de, da; çok",
  top: "zirve, üst", touched: "duygulandı, etkilendi", traditional: "geleneksel", traffic: "trafik",
  trail: "patika", transportation: "ulaşım", travel: "seyahat etmek", tried: "denedi",
  try: "denemek", turbines: "türbinler", turned: "döndü, çıktı", twenty: "yirmi", twice: "iki kez",
  two: "iki", under: "altında", understand: "anlamak", understanding: "anlama",
  university: "üniversite", unlike: "aksine", until: "-e kadar", up: "yukarı", use: "kullanmak",
  used: "kullanılan, kullandı", using: "kullanarak", usually: "genellikle", vague: "belirsiz",
  valley: "vadi", very: "çok", view: "manzara, görüş", visitors: "ziyaretçiler", waited: "bekledi",
  wanted: "istedi", wants: "ister", warmly: "sıcak bir şekilde", was: "idi", washing: "yıkama",
  waste: "atık", water: "su", ways: "yollar", we: "biz", wealthy: "zengin", wearing: "giyme",
  weather: "hava durumu", week: "hafta", welcomed: "hoş karşıladı", were: "idiler", wet: "ıslak",
  what: "ne", when: "ne zaman", which: "hangi", while: "iken", will: "-ecek, -acak",
  wind: "rüzgar", winter: "kış", wire: "tel", with: "ile", words: "kelimeler", work: "çalışmak, iş",
  worked: "çalıştı", workers: "işçiler", world: "dünya", would: "-erdi", write: "yazmak",
  writing: "yazma", year: "yıl", years: "yıllar", you: "sen, siz", zeynep: "Zeynep (isim)",
};
